{% set version = "2.7.1" %}

package:
  name: h5py
  version: {{ version }}

source:
  fn: h5py-{{ version }}.tar.gz
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: 55bdefda47c49973ec24384097d18eb5f84797c057aaf0bf0b6b0f7860ad43e7

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - hdf5 1.8.18|1.8.18.*
    - cython
    - six
    - pkgconfig

  run:
    - python
    - numpy x.x
    # when this is changed also update bld.bat
    - hdf5 1.8.18|1.8.18.*
    - six
    - unittest2    # [py26]

test:
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD 3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
