{% set version = "3.0.0" %}
{% set build = 0 %}

# mpi must be defined for conda-smithy lint
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prefer nompi builds via a build number offset
{% set build = build + 100 %}
{% endif %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: 5cd41229b92d2d40f6b73f6f927464f3ac1704be03f9eeb57b3152338f796e9e
  patches:
    # skip failing unicode test on windows
    - skip-failing-unicode-test.patch  # [win]

build:
  number: {{ build }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # Need to wait on numpy 1.19.3 build for Python 3.9 support
  skip: true  # [py==39]
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `pkg * mpi_mpich_*` for mpich
  # `hdf5 * mpi_*` for any mpi
  # `hdf5 * nompi_*` for no mpi
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    # h5py setup builds off these exact versions
    - numpy 1.12  # [py==36]
    - numpy 1.14.5  # [py==37]
    - numpy 1.17.5  # [py==38]
    - numpy 1.19.3  # [py>=39]
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    # need to list hdf5 twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - cython
    - pkgconfig
  run:
    - python
    - cached-property
    - numpy >=1.12.0  # [py==36]
    - numpy >=1.14.5  # [py==37]
    - numpy >=1.17.5  # [py==38]
    - numpy >=1.19.3  # [py>=39]
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    # hdf5 >=1.10.4 has run_exports
    - hdf5
    - pyreadline  # [win]

test:
  imports:
    - h5py
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - pytest-mpi

about:
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
  dev_url: https://github.com/h5py/h5py

extra:
  recipe-maintainers:
    - jakirkham
    - tacaswell
    - ocefpaf
    - minrk
    - scopatz
