travis:
  secure:
    BINSTAR_TOKEN: Vh66HWufGoTScrXYolm4L/QH6pSC5AzWZE/XxChrTPUaL11KCx1FcPeRUVbAiAitIKtD0L/SAy5JdmaBwU2IvWQYNmymiF2t6wtu/NcCrTKF2YkCok3rZY9Um+NDj0rFewBTJUXbh5Yahnf46t1Di2HWhiYQxfSdbrsJswHceaumfDlxzLs8HJMc1MJ/zYXts4trzJP7D8MWoOHbLgZDJ8BcPDDGalRDy6VvLKHt60jWhB75QZyCcYm/Giy5Zc3kkExuLg2bHX+c9a37j3ET6o/Ftf88MZ/nmzWPOtTEpHd0r6abPmKnUxT65prT02pdYPlfrVfZM6/s7ZpA+foL1sR7P3l88Lb4SRf7SD3BT/b6T/UkKimteVnMVbOOcZZabio2CKR4AiIJ8aqLRELXBdDVPvSApQ9frYZnzbrLIvaa618puiPn10pPr6OGJnMBxEEB8gPSTUA8dHZQZduEvwwKKmhu+7xBletKM5iHMxse5EmEZ80SWv72w8Q+pqyOhr6//y2xBksL1JNhQkmXPEvVPRefg8lZTDa5oaYBVGYUM2h4QwOnjlYK4QooXkCnhnHLcdQLerIgBCc8Ocvx7fMah6ltygRQD/vsQHD7RbdwWhbvvx2FnvY1Jpvx6b3ifjaFwKbK5V6sqMS7O4Im7IoLc2crlGPoYRdGwCLmWBw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
